server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: DermaClinic

  datasource:
    url: jdbc:postgresql://localhost:5432/dermaclinic_db
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:Asdf1234!}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 60000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: -1ms

  cache:
    type: redis
    redis:
      time-to-live: 60m
      cache-null-values: false
      use-key-prefix: true
      key-prefix: "dermaclinic:"

jwt:
  secret: ${JWT_SECRET:bHVuY2hkb3duaGFsZndheXNpbGVudHJpdmVydG9uZXJlZ2lvbnRvcHBvc3NpYmx5cmU=}
  expiry: ${JWT_EXPIRY:86400}   # seconds

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
